### ISSUE TITLE
NuGet package not compatible with .NET 4.5.2

### ISSUE THREAD

**Issue by nibe** [KirillOsenkov/Undo#3]
When I try to install the package `GuiLabs.Undo` in Visual Studio 2013, NuGet says it's not compatible with .NET 4.5.2. The same goes for .NET 4.6.1.

However, when I include the library manually it works beautifully. Perhaps the package info is wrong?

**Comment by KirillOsenkov** [comment]
Hey @terrajobst can I ask you for a huge small favor?

This library is as simple as it gets.

There's a csproj:
https://github.com/KirillOsenkov/Undo/blob/master/src/UndoFramework/UndoFramework.csproj
and there's a nuspec:
https://github.com/KirillOsenkov/Undo/blob/master/src/UndoFramework/Guilabs.Undo.nuspec

Can you tell me how to make it a "canonical" library that I can use everywhere? Ideally a small PR please ;)

**Comment by heroius** [comment]
you should modify the project's target framework to .net framework 4, this will support all 4.x versions ( for now >4.5 only )

**Comment by vernou** [comment]
Maybe it's time to port to .NET Standard?

**Comment by KirillOsenkov** [comment]
The library is now netstandard2.0. Any chance you could upgrade your project to .NET 4.6.1 that supports netstandard2.0?

https://docs.microsoft.com/en-us/dotnet/standard/net-standard
